### ISSUE TITLE
Not a real problem, but a bug. 

### ISSUE THREAD

**Issue by gustavosmendes** [AnKing-VIP/anki-field-autocomplete#3] opened 2021-09-07 17:25 UTC
#### Problem description

I just typed "\" at one field and this error happens. If I close the window of the "error", just keeps it fine. Yesterday the same happened with the " symbol. 
Not a real problem.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
2.1.47
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2021-09-07 00:54:01

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 589, in _onBridgeCmd
  File "aqt\hooks_gen.py", line 4000, in __call__
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 26, in handle_bridge_commands
    if handle_autocomplete(cmd, editor):
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 65, in handle_autocomplete
    nids = col.find_notes(query)
  File "anki\collection.py", line 503, in find_notes
  File "anki\_backend\generated.py", line 762, in search_notes
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨the escape sequence <code>⁨\ ⁩</code> is not defined. If you want to search for a literal backslash <code>\</code>, prepend another one: <code>\\</code>.⁩</p>

```

```

**Comment by gustavosmendes** [comment] 2021-09-07 17:26
Also, I didn't try to search anything at autocomplete at those times. 

The problem does not occur again when I try to type the same symbol, even when restarted.

**Comment by RisingOrange** [comment] 2021-09-07 18:57
The issue is fixed now. Thanks for reporting!

**Closed as completed** 2021-09-07 18:56 UTC
Labels: bug

**Comment by gustavosmendes** [comment] 2021-09-08 00:08
@RisingOrange I looked at the log. Please, I meant that the add-on was not currently active for search. I don't understand about programming, but I hope the situation will be clearer if future bugs arise.

**Comment by gustavosmendes** [comment] 2021-09-08 01:06
Happened again, even after update. 


Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2021-09-07 00:54:01

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 589, in _onBridgeCmd
  File "aqt\hooks_gen.py", line 4000, in __call__
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 26, in handle_bridge_commands
    if handle_autocomplete(cmd, editor):
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 65, in handle_autocomplete
    nids = col.find_notes(query)
  File "anki\collection.py", line 503, in find_notes
  File "anki\_backend\generated.py", line 762, in search_notes
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨an opening double quote <code>"</code> was found, but there was no second one to close it. If you want to search for a literal <code>"</code>, prepend a backslash: <code>\"</code>.⁩</p>



I tested it with all addons disabled... This time, the symbol was ' and ".  You can reproduce if you type ';" (single quote and after a double quote). 
Also, the add-on really stop working, now it's a real bug
